pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh('./gradlew build')
            }
        }
        stage('Build Docker Image') {
            steps {
               sh('sudo docker build -t madurad/hello-world-docker:$BUILD_NUMBER .')
            }
        }
        stage('Push Docker Image') {
            steps {
                sh('sudo docker push madurad/hello-world-docker:$BUILD_NUMBER')
            }
        }
    }
}