pipeline {
    agent any

    stages {
        stage('git clone') {
            steps {
               git credentialsId: 'dockerhub', url: 'https://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@github.com/Nagarajan-Santhosh/java-gradle-project.git/'
            }
        }
        stage('Build Docker Image') {
            steps {
               sh('sudo docker build -t santhoshsp/hello-world-docker:$BUILD_NUMBER .')
            }
        }
        stage('Push Docker Image') {
            steps {
                sh('sudo docker push santhoshsp/hello-world-docker:$BUILD_NUMBER')
            }
        }
    }
}
